site_name: 攀登
site_url: https://jie-taoying.github.io/
site_author: 揭涛英
site_description: 分享学习、技能、实践等方面的经验与思考

theme:
  name: material
  custom_dir: docs/overrides #覆写路径
  palette:
    - scheme: default
      primary: deep blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  font:
    text: Roboto
    code: Roboto Mono
  language: zh
  logo: https://s1.imagehub.cc/images/2025/07/28/ad2070c0e012973beba367ce4ebbe404.jpeg
  favicon: https://s1.imagehub.cc/images/2025/07/28/ad2070c0e012973beba367ce4ebbe404.jpeg

extra:
  alternate:
    - name: 中文
      link: "javascript:translate.changeLanguage('chinese_simplified');"
      lang: zh
    - name: 繁體中文 (台灣)
      link: "javascript:translate.changeLanguage('chinese_traditional_taiwan');"
      lang: zh-TW
    - name: English
      link: "javascript:translate.changeLanguage('english');"
      lang: en
    

  features:
    - announce.dismiss
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
    - navigation.indexes
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github
    logo: logo

edit_uri: edit/main/docs
repo_url: https://github.com/Jie-Taoying/Jie-Taoying.github.io
repo_name: Jie-Taoying.github.io

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jie-Taoying
    - icon: fontawesome/brands/weixin
      link: https://s1.imagehub.cc/images/2025/07/26/4e9e072b52e963d4c149f3c3edca3388.jpg
      name: 微信二维码
    - icon: fontawesome/solid/envelope
      link: mailto:2026125544@qq.com
      name: QQ邮箱


plugins:
  - search
  - blog:
      post_date_format: full
      post_readtime: true 
  - tags:
      tags_file: tag.md  # 分类标签

nav:
  - 首页: index.md
  - 学习:
    - 金句摘抄: study/article.md
    - 书籍推荐: study/book.md
  - 博客: 
    - blog/index.md
  - 标签: tag.md
  - 我的:
    - 关于我: 关于我/My.md

markdown_extensions: #详见https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ 和 https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # 支持Markdown文件上方自定义标题标签等
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex: # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - markdown.extensions.toc:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  #     permalink: "\ue157"

# extra_javascript:
  # - javascripts/extra.js #自定义javascript


extra_css:
  - stylesheets/extra.css # 自定义CSS
