site_name: 攀登
site_url: https://jie-taoying.github.io/
site_author: 揭涛英
theme:
  name: material
  palette:
    # primary: 'deep blue'
    # accent: 'red'

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
  language: zh
  logo: https://s1.imagehub.cc/images/2025/07/28/ad2070c0e012973beba367ce4ebbe404.jpeg
  favicon: https://s1.imagehub.cc/images/2025/07/28/ad2070c0e012973beba367ce4ebbe404.jpeg

  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate
  language: zh # 一些提示性的文字会变成中文

  icon:
    repo: fontawesome/brands/github #右上角图标
    logo: logo

edit_uri: edit/main/docs  # 编辑按钮跳转的链接
repo_url: https://github.com/Jie-Taoying/Jie-Taoying.github.io  # 右上角点击跳转的链接
repo_name: Jie-Taoying.github.io  # 右上角显示的名字

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk #Mkdocs原作者

plugins:
  - search
  - blog
  - tags

nav:
  - 首页: 
    - index.md
  - study:
    - 金句摘抄: study/article.md
    - 书籍推荐: study/book.md
  - blog:
    - index.md
  