# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
# 遵循Material主题的JSON Schema校验，确保配置格式正确

# ==============================================
# 1. 站点基础信息配置
# ==============================================
site_name: 攀登                  # 站点名称
site_description: 分享学习、技能、实践等方面的经验与思考  # 站点描述（SEO相关）
site_author: 揭涛英                  # 站点作者


# ==============================================
# 2. 主题配置（基于Material主题）
# ==============================================
theme:
  logo: https://www.helloimg.com/i/2025/07/27/6886346c6df88.jpeg  # 站点logo图片
  favicon: https://www.helloimg.com/i/2025/07/27/6886346c6df88.jpeg  # 浏览器标签页图标
  name: material                     # 使用Material主题
  language: zh                       # 站点默认语言（中文）
  custom_dir: docs/overrides         # 自定义主题覆盖目录
  features:                          # 启用的主题功能
    - navigation.tabs                # 顶部导航标签页
    - navigation.top                 # 回到顶部按钮
    - search.suggest                 # 搜索建议
    - search.highlight               # 搜索结果高亮
    - content.code.copy              # 代码块复制按钮
    - content.code.select            # 代码块选择功能
  palette:                           # 主题配色方案（支持明暗模式自动切换）
    - media: "(prefers-color-scheme: light)"  # 日间模式
      scheme: default
      primary: deep blue                  # 主色调（深蓝色）
      accent: indigo                 # 强调色（靛蓝色）
      toggle:
        icon: material/brightness-7  # 切换图标
        name: 切换至夜间模式
    - media: "(prefers-color-scheme: dark)"   # 夜间模式
      scheme: slate
      primary: black                 # 主色调（黑色）
      accent: indigo                 # 强调色（靛蓝色）
      toggle:
        icon: material/brightness-4  # 切换图标
        name: 切换至日间模式


# ==============================================
# 3. 导航结构配置（定义站点页面层级）
# ==============================================
nav:
  - 主页: 
    - 首页: index.md
  - 经验心得:
      - 专业知识: 经验心得/learning/professional.md  # 路径分隔符改为 /
      - 技能提升: 经验心得/learning/skills.md        # 路径分隔符改为 /
  - 文汇撷英:
      - 明理书摘: 文汇撷英/明理书摘/articles.md
      - 格物荐书: 文汇撷英/格物荐书/books.md
      
  - 关于我: about.md


# ==============================================
# 4. 仓库与编辑配置（关联GitHub仓库）
# ==============================================
repo_url: https://github.com/jie-taoying/jie-taoying.github.io  # 仓库地址
repo_name: jie-taoying.github.io                                # 仓库名称（显示用）
edit_uri: edit/main/docs                                        # 页面编辑链接（点击可跳转到GitHub编辑页面）


# ==============================================
# 5. 额外配置（多语言、社交链接等）
# ==============================================
extra:
  generator: false                   # 隐藏页脚的"MkDocs制造"标识
  alternate:                         # 多语言切换配置
    - name: 简体中文
      link: "javascript:translate.changeLanguage('chinese_simplified');"
      lang: zh
    - name: 繁體中文  # 新增的繁体中文选项
      link: "javascript:translate.changeLanguage('chinese_traditional');"  # 假设翻译函数支持这个参数
      lang: zh-TW  # 繁体中文的语言代码
    - name: English
      link: "javascript:translate.changeLanguage('english');"
      lang: en
    - name: 한국어
      link: "javascript:translate.changeLanguage('korean');"
      lang: ko
    - name: 日本語
      link: "javascript:translate.changeLanguage('japanese');"
      lang: ja
    - name: بالعربية
      link: "javascript:translate.changeLanguage('arabic');"
      lang: ar
    - name: Deutsch
      link: "javascript:translate.changeLanguage('german');"
      lang: de
    - name: Français
      link: "javascript:translate.changeLanguage('french');"
      lang: fr
    - name: Español
      link: "javascript:translate.changeLanguage('spanish');"
      lang: es
    - name: português
      link: "javascript:translate.changeLanguage('portuguese');"
      lang: pt
  social:                            # 社交链接（页脚显示）
    - icon: fontawesome/brands/github
      link: https://github.com/jie-taoying
    - icon: fontawesome/brands/weixin
      link: https://s1.imagehub.cc/images/2025/07/26/4e9e072b52e963d4c149f3c3edca3388.jpg
      name: 微信二维码
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/wcowin_
    - icon: fontawesome/regular/envelope
      link: mailto:2026125544@qq.com
      name: QQ 邮箱


# ==============================================
# 6. 插件配置（增强站点功能）
# ==============================================
plugins:
  - search                           # 内置搜索插件
  - git-revision-date-localized:     # 显示页面最后更新时间
      type: iso_date                 # 时间格式（ISO标准格式）
  - blog:                            # 博客功能插件
      post_date_format: full         # 文章日期显示格式（完整格式）
      post_readtime: true            # 显示文章阅读时间
  - tags                             # 标签功能插件
  - document-dates:                  # 文档日期插件
      position: top                  # 显示位置：top（标题后） bottom（文档末尾），默认：bottom
      type: date                     # 时间类型：date datetime timeago，默认：date
      locale: zh                     # 本地化语言：en zh zh_TW es fr de ar ja ko ru，默认：en
      date_format: '%Y-%m-%d'        # 日期格式化字符串，例如：%Y年%m月%d日、%b %d, %Y
      time_format: '%H:%M:%S'        # 时间格式化字符串（仅在 type=datetime 时有效）
      exclude:                       # 排除文件列表，默认为空
        - temp.md                    # 排除指定文件
        - private/*                  # 排除 private 目录下所有文件，包括子目录
      show_author: true              # 是否显示作者信息，默认：true


# ==============================================
# 7. Markdown扩展配置（支持更多格式语法）
# ==============================================
markdown_extensions:
  - abbr                             # 支持缩写语法（*[HTML]: Hyper Text Markup Language）
  - attr_list                        # 支持为元素添加属性（如{: #id .class}）
  - admonition                       # 支持提示框（如!!! note "标题"）
  - def_list                         # 支持定义列表（术语: 解释）
  - footnotes                        # 支持脚注（[^1] + [^1]: 内容）
  - md_in_html                       # 支持在HTML中嵌套Markdown
  - pymdownx.caret                   # 支持上下标（^上标^ 和 ~下标~）
  - pymdownx.betterem                # 优化强调语法（**加粗**/*斜体*）
  - pymdownx.critic                  # 支持编辑批注（{--删除--} {++添加++}）
  - pymdownx.details                 # 支持折叠块（??? 标题）
  - pymdownx.inlinehilite            # 支持行内代码高亮（`#!python print()`）
  - pymdownx.keys                    # 支持快捷键显示（++ctrl+alt+del++）
  - pymdownx.mark                    # 支持标记文本（==标记内容==）
  - pymdownx.snippets                # 支持导入外部代码片段（--8<-- "filename"）
  - pymdownx.smartsymbols            # 自动替换特殊符号（如->替换为→）
  - pymdownx.tilde                   # 支持删除线（~~删除内容~~）
  - pymdownx.superfences:            # 支持代码块嵌套和扩展语法
      custom_fences:
        - name: mermaid              # 支持mermaid流程图
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:             # 支持LaTeX数学公式
      generic: true
  - toc:                             # 自动生成目录
      permalink: true                # 为标题添加锚点链接
  - pymdownx.highlight:              # 代码块高亮配置
      anchor_linenums: true          # 行号添加锚点
      linenums: true                 # 显示行号
  - pymdownx.emoji:                  # 支持emoji表情
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:                 # 支持标签页语法
      alternate_style: true          # 使用交替样式
  - pymdownx.tasklist:               # 支持任务列表
      custom_checkbox: true          # 使用自定义复选框样式


# ==============================================
# 8. 自定义资源（JS/CSS）
# ==============================================
extra_javascript:
  - javascripts/extra.js  # 自定义JavaScript脚本
  - js/translate_config.js             # 翻译配置脚本
  - js/analytics.js                    # 百度统计脚本
extra_css:
  - extra.css             # 自定义CSS样式


# ==============================================
# 9. 钩子配置（自定义Python脚本）
# ==============================================
hooks:
  - docs/overrides/hooks/reading_time.py  # 阅读时间统计


# ==============================================
# 10. 底部版权信息
# ==============================================
copyright: Copyright &copy; 2025 JTY  # 版权声明
